trigger:
    tags:
      include:
        - v*
    branches:
      include:
        - master
jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 12.x
      - script: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm install
          cd ./src
          npm install
          npm run build
          cp -r ./dist ../lib
          cd ..
        displayName: Install dependencies and build
        env:
          NPM_TOKEN: $(NPM_TOKEN)
      - script: >
          echo $(./node_modules/.bin/git-tag-version)

          yarn publish --new-version $(./node_modules/.bin/git-tag-version)
          --no-git-tag-version --access public
        env:
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release
        condition: >-
          and(succeeded(), startsWith(variables['Build.SourceBranch'],
          'refs/tags'))
  