trigger:
    tags:
      include:
        - v*
    branches:
      include:
        - master
jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseNode@1
        inputs:
          version: 22.x
      - script: npm ci
        displayName: Clean install dependencies
      - script: npx playwright install --with-deps
        displayName: 'Install Playwright browsers'
      - script: npm run lint
        displayName: Run lint
      - script: npm run build-ts
        displayName: Run typescript build
      - script: npm run test
        displayName: Run node and browser tests
      - script: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        displayName: Write npm token to npmrc
        env:
          NPM_TOKEN: $(NPM_TOKEN)
      - script: |
          ./scripts/publish.sh
        env:
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release
        condition: >-
          and(succeeded(), startsWith(variables['Build.SourceBranch'],
          'refs/tags'))
