trigger:
    tags:
      include:
        - v*
    branches:
      include:
        - master
jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 18.x
      - script: |
          npm install \
          && npm run lint \
          && npm run build-ts \
          && npm run test
        displayName: Install dependencies, build and run tests
      - script: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        displayName: Write npm token to npmrc
        env:
          NPM_TOKEN: $(NPM_TOKEN)
      - script: |
          ./scripts/publish.sh
        env:
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release
        condition: >-
          and(succeeded(), startsWith(variables['Build.SourceBranch'],
          'refs/tags'))
