trigger:
    tags:
      include:
        - v*
    branches:
      include:
        - master
jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
      - script: |
          npm install
        displayName: Install dependencies and run tests
      - script: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        displayName: Write npm token to npmrc
        env:
          NPM_TOKEN: $(NPM_TOKEN)
      - script: |
          ./scripts/publish.sh
        env:
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release
        condition: >-
          and(succeeded(), startsWith(variables['Build.SourceBranch'],
          'refs/tags'))
