trigger:
    tags:
      include:
        - v*
    branches:
      include:
        - master
jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 14.x
      - script: |
          npm install
          npm run test
        displayName: Install dependencies and run tests
      - script: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        displayName: Write npm token to npmrc
        env:
          NPM_TOKEN: $(NPM_TOKEN)
      - script: |
          latestGitTag=$(git describe --tags --abbrev=0)
          latestGitTag="${latestGitTag:1}"
          echo $latestGitTag
          if [[ $latestGitTag == *"beta"* ]];
          then
          echo "Publishing beta version";
          yarn publish --new-version $latestGitTag --no-git-tag-version --access public --tag beta
          else
          echo "Publishing new version $latestGitTag";
          yarn publish --new-version $latestGitTag --no-git-tag-version --access public
          fi
        env:
          NPM_TOKEN: $(NPM_TOKEN)
        displayName: Release
        condition: >-
          and(succeeded(), startsWith(variables['Build.SourceBranch'],
          'refs/tags'))
