"use strict";
/* tslint:disable */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataBox = exports.ArrayMetadata = exports.ArrayMetadata_MetadataEntry = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = __importStar(require("capnp-ts"));
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "b57d9224b587d87f";
class ArrayMetadata_MetadataEntry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getType() { return capnp_ts_1.Struct.getText(1, this); }
    setType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getValueNum() { return capnp_ts_1.Struct.getUint32(0, this); }
    setValueNum(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(2, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getDel() { return capnp_ts_1.Struct.getBit(32, this); }
    setDel(value) { capnp_ts_1.Struct.setBit(32, value, this); }
    toString() { return "ArrayMetadata_MetadataEntry_" + super.toString(); }
}
exports.ArrayMetadata_MetadataEntry = ArrayMetadata_MetadataEntry;
ArrayMetadata_MetadataEntry._capnp = { displayName: "MetadataEntry", id: "926fe1c3b12ed651", size: new capnp_ts_1.ObjectSize(8, 3) };
class ArrayMetadata extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, ArrayMetadata._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, ArrayMetadata._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ArrayMetadata_" + super.toString(); }
}
exports.ArrayMetadata = ArrayMetadata;
ArrayMetadata.MetadataEntry = ArrayMetadata_MetadataEntry;
ArrayMetadata._capnp = { displayName: "ArrayMetadata", id: "9737dcafdfce31bb", size: new capnp_ts_1.ObjectSize(0, 1) };
class DataBox extends capnp_ts_1.Struct {
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(0, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "DataBox_" + super.toString(); }
}
exports.DataBox = DataBox;
DataBox._capnp = { displayName: "DataBox", id: "9983d93d37709d16", size: new capnp_ts_1.ObjectSize(0, 1) };
ArrayMetadata._Entries = capnp.CompositeList(ArrayMetadata_MetadataEntry);
//# sourceMappingURL=arrayMetadata.capnp.js.map