"use strict";
/* tslint:disable */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrayMetadata = exports.ArrayMetadata_MetadataEntry = exports.AttributeBufferSize = exports.MapUInt64 = exports.MapUInt64_Entry = exports.MapFloat64 = exports.MapFloat64_Entry = exports.DomainArray = exports.Condition = exports.ConditionClause = exports.ReadState = exports.SubarrayPartitioner = exports.SubarrayPartitioner_State = exports.SubarrayPartitioner_PartitionInfo = exports.Subarray = exports.SubarrayRanges = exports.QueryReader = exports.Writer = exports.Stats = exports.Config = exports.KV = exports.Map = exports.Map_Entry = exports.ArraySchemaMap = exports.ArraySchemaMap_Entry = exports.FilterPipeline = exports.Filter = exports.Filter_Data = exports.Filter_Data_Which = exports.ArraySchema = exports.ArrayOpen = exports.Array = exports.Domain = exports.Dimension = exports.Dimension_TileExtent = exports.Dimension_TileExtent_Which = exports.AttributeBufferHeader = exports.Attribute = exports.NonEmptyDomainList = exports.NonEmptyDomain = exports.Query = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = __importStar(require("capnp-ts"));
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "b57d9224b587d87e";
class Query extends capnp_ts_1.Struct {
    adoptAttributeBufferHeaders(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownAttributeBufferHeaders() { return capnp_ts_1.Struct.disown(this.getAttributeBufferHeaders()); }
    getAttributeBufferHeaders() { return capnp_ts_1.Struct.getList(0, Query._AttributeBufferHeaders, this); }
    hasAttributeBufferHeaders() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initAttributeBufferHeaders(length) { return capnp_ts_1.Struct.initList(0, Query._AttributeBufferHeaders, length, this); }
    setAttributeBufferHeaders(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getLayout() { return capnp_ts_1.Struct.getText(1, this); }
    setLayout(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getStatus() { return capnp_ts_1.Struct.getText(2, this); }
    setStatus(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getType() { return capnp_ts_1.Struct.getText(3, this); }
    setType(value) { capnp_ts_1.Struct.setText(3, value, this); }
    adoptWriter(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownWriter() { return capnp_ts_1.Struct.disown(this.getWriter()); }
    getWriter() { return capnp_ts_1.Struct.getStruct(4, Writer, this); }
    hasWriter() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initWriter() { return capnp_ts_1.Struct.initStructAt(4, Writer, this); }
    setWriter(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptReader(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownReader() { return capnp_ts_1.Struct.disown(this.getReader()); }
    getReader() { return capnp_ts_1.Struct.getStruct(5, QueryReader, this); }
    hasReader() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initReader() { return capnp_ts_1.Struct.initStructAt(5, QueryReader, this); }
    setReader(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    adoptArray(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(6, this)); }
    disownArray() { return capnp_ts_1.Struct.disown(this.getArray()); }
    getArray() { return capnp_ts_1.Struct.getStruct(6, Array, this); }
    hasArray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(6, this)); }
    initArray() { return capnp_ts_1.Struct.initStructAt(6, Array, this); }
    setArray(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(6, this)); }
    getTotalFixedLengthBufferBytes() { return capnp_ts_1.Struct.getUint64(0, this); }
    setTotalFixedLengthBufferBytes(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getTotalVarLenBufferBytes() { return capnp_ts_1.Struct.getUint64(8, this); }
    setTotalVarLenBufferBytes(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getTotalValidityBufferBytes() { return capnp_ts_1.Struct.getUint64(16, this); }
    setTotalValidityBufferBytes(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getVarOffsetsMode() { return capnp_ts_1.Struct.getText(7, this); }
    setVarOffsetsMode(value) { capnp_ts_1.Struct.setText(7, value, this); }
    getVarOffsetsAddExtraElement() { return capnp_ts_1.Struct.getBit(192, this); }
    setVarOffsetsAddExtraElement(value) { capnp_ts_1.Struct.setBit(192, value, this); }
    getVarOffsetsBitsize() { return capnp_ts_1.Struct.getInt32(28, this); }
    setVarOffsetsBitsize(value) { capnp_ts_1.Struct.setInt32(28, value, this); }
    adoptConfig(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(8, this)); }
    disownConfig() { return capnp_ts_1.Struct.disown(this.getConfig()); }
    getConfig() { return capnp_ts_1.Struct.getStruct(8, Config, this); }
    hasConfig() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(8, this)); }
    initConfig() { return capnp_ts_1.Struct.initStructAt(8, Config, this); }
    setConfig(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(8, this)); }
    adoptStats(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this)); }
    disownStats() { return capnp_ts_1.Struct.disown(this.getStats()); }
    getStats() { return capnp_ts_1.Struct.getStruct(9, Stats, this); }
    hasStats() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initStats() { return capnp_ts_1.Struct.initStructAt(9, Stats, this); }
    setStats(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this)); }
    toString() { return "Query_" + super.toString(); }
}
exports.Query = Query;
Query._capnp = { displayName: "Query", id: "ea34268ae031ac7a", size: new capnp_ts_1.ObjectSize(32, 10) };
class NonEmptyDomain extends capnp_ts_1.Struct {
    adoptNonEmptyDomain(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownNonEmptyDomain() { return capnp_ts_1.Struct.disown(this.getNonEmptyDomain()); }
    getNonEmptyDomain() { return capnp_ts_1.Struct.getStruct(0, DomainArray, this); }
    hasNonEmptyDomain() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initNonEmptyDomain() { return capnp_ts_1.Struct.initStructAt(0, DomainArray, this); }
    setNonEmptyDomain(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getIsEmpty() { return capnp_ts_1.Struct.getBit(0, this); }
    setIsEmpty(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    adoptSizes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSizes() { return capnp_ts_1.Struct.disown(this.getSizes()); }
    getSizes() { return capnp_ts_1.Struct.getList(1, capnp.Uint64List, this); }
    hasSizes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSizes(length) { return capnp_ts_1.Struct.initList(1, capnp.Uint64List, length, this); }
    setSizes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "NonEmptyDomain_" + super.toString(); }
}
exports.NonEmptyDomain = NonEmptyDomain;
NonEmptyDomain._capnp = { displayName: "NonEmptyDomain", id: "8ee6e91f0369a459", size: new capnp_ts_1.ObjectSize(8, 2) };
class NonEmptyDomainList extends capnp_ts_1.Struct {
    adoptNonEmptyDomains(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownNonEmptyDomains() { return capnp_ts_1.Struct.disown(this.getNonEmptyDomains()); }
    getNonEmptyDomains() { return capnp_ts_1.Struct.getList(0, NonEmptyDomainList._NonEmptyDomains, this); }
    hasNonEmptyDomains() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initNonEmptyDomains(length) { return capnp_ts_1.Struct.initList(0, NonEmptyDomainList._NonEmptyDomains, length, this); }
    setNonEmptyDomains(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "NonEmptyDomainList_" + super.toString(); }
}
exports.NonEmptyDomainList = NonEmptyDomainList;
NonEmptyDomainList._capnp = { displayName: "NonEmptyDomainList", id: "ec4d493d30f4b23d", size: new capnp_ts_1.ObjectSize(0, 1) };
class Attribute extends capnp_ts_1.Struct {
    getCellValNum() { return capnp_ts_1.Struct.getUint32(0, this); }
    setCellValNum(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getType() { return capnp_ts_1.Struct.getText(1, this); }
    setType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptFilterPipeline(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownFilterPipeline() { return capnp_ts_1.Struct.disown(this.getFilterPipeline()); }
    getFilterPipeline() { return capnp_ts_1.Struct.getStruct(2, FilterPipeline, this); }
    hasFilterPipeline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initFilterPipeline() { return capnp_ts_1.Struct.initStructAt(2, FilterPipeline, this); }
    setFilterPipeline(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptFillValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownFillValue() { return capnp_ts_1.Struct.disown(this.getFillValue()); }
    getFillValue() { return capnp_ts_1.Struct.getData(3, this); }
    hasFillValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initFillValue(length) { return capnp_ts_1.Struct.initData(3, length, this); }
    setFillValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    getNullable() { return capnp_ts_1.Struct.getBit(32, this); }
    setNullable(value) { capnp_ts_1.Struct.setBit(32, value, this); }
    getFillValueValidity() { return capnp_ts_1.Struct.getBit(33, this); }
    setFillValueValidity(value) { capnp_ts_1.Struct.setBit(33, value, this); }
    toString() { return "Attribute_" + super.toString(); }
}
exports.Attribute = Attribute;
Attribute._capnp = { displayName: "Attribute", id: "c3c6d96fc6043315", size: new capnp_ts_1.ObjectSize(8, 4) };
class AttributeBufferHeader extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getFixedLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFixedLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getVarLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(8, this); }
    setVarLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getValidityLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(16, this); }
    setValidityLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    getOriginalFixedLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(24, this); }
    setOriginalFixedLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    getOriginalVarLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(32, this); }
    setOriginalVarLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(32, value, this); }
    getOriginalValidityLenBufferSizeInBytes() { return capnp_ts_1.Struct.getUint64(40, this); }
    setOriginalValidityLenBufferSizeInBytes(value) { capnp_ts_1.Struct.setUint64(40, value, this); }
    toString() { return "AttributeBufferHeader_" + super.toString(); }
}
exports.AttributeBufferHeader = AttributeBufferHeader;
AttributeBufferHeader._capnp = { displayName: "AttributeBufferHeader", id: "9884df9a1b40f364", size: new capnp_ts_1.ObjectSize(48, 1) };
var Dimension_TileExtent_Which;
(function (Dimension_TileExtent_Which) {
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["INT8"] = 0] = "INT8";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["UINT8"] = 1] = "UINT8";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["INT16"] = 2] = "INT16";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["UINT16"] = 3] = "UINT16";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["INT32"] = 4] = "INT32";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["UINT32"] = 5] = "UINT32";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["INT64"] = 6] = "INT64";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["UINT64"] = 7] = "UINT64";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["FLOAT32"] = 8] = "FLOAT32";
    Dimension_TileExtent_Which[Dimension_TileExtent_Which["FLOAT64"] = 9] = "FLOAT64";
})(Dimension_TileExtent_Which = exports.Dimension_TileExtent_Which || (exports.Dimension_TileExtent_Which = {}));
class Dimension_TileExtent extends capnp_ts_1.Struct {
    getInt8() {
        capnp_ts_1.Struct.testWhich("int8", capnp_ts_1.Struct.getUint16(2, this), 0, this);
        return capnp_ts_1.Struct.getInt8(1, this);
    }
    isInt8() { return capnp_ts_1.Struct.getUint16(2, this) === 0; }
    setInt8(value) {
        capnp_ts_1.Struct.setUint16(2, 0, this);
        capnp_ts_1.Struct.setInt8(1, value, this);
    }
    getUint8() {
        capnp_ts_1.Struct.testWhich("uint8", capnp_ts_1.Struct.getUint16(2, this), 1, this);
        return capnp_ts_1.Struct.getUint8(1, this);
    }
    isUint8() { return capnp_ts_1.Struct.getUint16(2, this) === 1; }
    setUint8(value) {
        capnp_ts_1.Struct.setUint16(2, 1, this);
        capnp_ts_1.Struct.setUint8(1, value, this);
    }
    getInt16() {
        capnp_ts_1.Struct.testWhich("int16", capnp_ts_1.Struct.getUint16(2, this), 2, this);
        return capnp_ts_1.Struct.getInt16(4, this);
    }
    isInt16() { return capnp_ts_1.Struct.getUint16(2, this) === 2; }
    setInt16(value) {
        capnp_ts_1.Struct.setUint16(2, 2, this);
        capnp_ts_1.Struct.setInt16(4, value, this);
    }
    getUint16() {
        capnp_ts_1.Struct.testWhich("uint16", capnp_ts_1.Struct.getUint16(2, this), 3, this);
        return capnp_ts_1.Struct.getUint16(4, this);
    }
    isUint16() { return capnp_ts_1.Struct.getUint16(2, this) === 3; }
    setUint16(value) {
        capnp_ts_1.Struct.setUint16(2, 3, this);
        capnp_ts_1.Struct.setUint16(4, value, this);
    }
    getInt32() {
        capnp_ts_1.Struct.testWhich("int32", capnp_ts_1.Struct.getUint16(2, this), 4, this);
        return capnp_ts_1.Struct.getInt32(4, this);
    }
    isInt32() { return capnp_ts_1.Struct.getUint16(2, this) === 4; }
    setInt32(value) {
        capnp_ts_1.Struct.setUint16(2, 4, this);
        capnp_ts_1.Struct.setInt32(4, value, this);
    }
    getUint32() {
        capnp_ts_1.Struct.testWhich("uint32", capnp_ts_1.Struct.getUint16(2, this), 5, this);
        return capnp_ts_1.Struct.getUint32(4, this);
    }
    isUint32() { return capnp_ts_1.Struct.getUint16(2, this) === 5; }
    setUint32(value) {
        capnp_ts_1.Struct.setUint16(2, 5, this);
        capnp_ts_1.Struct.setUint32(4, value, this);
    }
    getInt64() {
        capnp_ts_1.Struct.testWhich("int64", capnp_ts_1.Struct.getUint16(2, this), 6, this);
        return capnp_ts_1.Struct.getInt64(8, this);
    }
    isInt64() { return capnp_ts_1.Struct.getUint16(2, this) === 6; }
    setInt64(value) {
        capnp_ts_1.Struct.setUint16(2, 6, this);
        capnp_ts_1.Struct.setInt64(8, value, this);
    }
    getUint64() {
        capnp_ts_1.Struct.testWhich("uint64", capnp_ts_1.Struct.getUint16(2, this), 7, this);
        return capnp_ts_1.Struct.getUint64(8, this);
    }
    isUint64() { return capnp_ts_1.Struct.getUint16(2, this) === 7; }
    setUint64(value) {
        capnp_ts_1.Struct.setUint16(2, 7, this);
        capnp_ts_1.Struct.setUint64(8, value, this);
    }
    getFloat32() {
        capnp_ts_1.Struct.testWhich("float32", capnp_ts_1.Struct.getUint16(2, this), 8, this);
        return capnp_ts_1.Struct.getFloat32(4, this);
    }
    isFloat32() { return capnp_ts_1.Struct.getUint16(2, this) === 8; }
    setFloat32(value) {
        capnp_ts_1.Struct.setUint16(2, 8, this);
        capnp_ts_1.Struct.setFloat32(4, value, this);
    }
    getFloat64() {
        capnp_ts_1.Struct.testWhich("float64", capnp_ts_1.Struct.getUint16(2, this), 9, this);
        return capnp_ts_1.Struct.getFloat64(8, this);
    }
    isFloat64() { return capnp_ts_1.Struct.getUint16(2, this) === 9; }
    setFloat64(value) {
        capnp_ts_1.Struct.setUint16(2, 9, this);
        capnp_ts_1.Struct.setFloat64(8, value, this);
    }
    toString() { return "Dimension_TileExtent_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(2, this); }
}
exports.Dimension_TileExtent = Dimension_TileExtent;
Dimension_TileExtent.INT8 = Dimension_TileExtent_Which.INT8;
Dimension_TileExtent.UINT8 = Dimension_TileExtent_Which.UINT8;
Dimension_TileExtent.INT16 = Dimension_TileExtent_Which.INT16;
Dimension_TileExtent.UINT16 = Dimension_TileExtent_Which.UINT16;
Dimension_TileExtent.INT32 = Dimension_TileExtent_Which.INT32;
Dimension_TileExtent.UINT32 = Dimension_TileExtent_Which.UINT32;
Dimension_TileExtent.INT64 = Dimension_TileExtent_Which.INT64;
Dimension_TileExtent.UINT64 = Dimension_TileExtent_Which.UINT64;
Dimension_TileExtent.FLOAT32 = Dimension_TileExtent_Which.FLOAT32;
Dimension_TileExtent.FLOAT64 = Dimension_TileExtent_Which.FLOAT64;
Dimension_TileExtent._capnp = { displayName: "tileExtent", id: "e669e109ac3471bd", size: new capnp_ts_1.ObjectSize(16, 4) };
class Dimension extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getNullTileExtent() { return capnp_ts_1.Struct.getBit(0, this); }
    setNullTileExtent(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getType() { return capnp_ts_1.Struct.getText(1, this); }
    setType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getTileExtent() { return capnp_ts_1.Struct.getAs(Dimension_TileExtent, this); }
    initTileExtent() { return capnp_ts_1.Struct.getAs(Dimension_TileExtent, this); }
    adoptDomain(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownDomain() { return capnp_ts_1.Struct.disown(this.getDomain()); }
    getDomain() { return capnp_ts_1.Struct.getStruct(2, DomainArray, this); }
    hasDomain() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initDomain() { return capnp_ts_1.Struct.initStructAt(2, DomainArray, this); }
    setDomain(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptFilterPipeline(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownFilterPipeline() { return capnp_ts_1.Struct.disown(this.getFilterPipeline()); }
    getFilterPipeline() { return capnp_ts_1.Struct.getStruct(3, FilterPipeline, this); }
    hasFilterPipeline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initFilterPipeline() { return capnp_ts_1.Struct.initStructAt(3, FilterPipeline, this); }
    setFilterPipeline(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "Dimension_" + super.toString(); }
}
exports.Dimension = Dimension;
Dimension._capnp = { displayName: "Dimension", id: "8740d96d749301b9", size: new capnp_ts_1.ObjectSize(16, 4) };
class Domain extends capnp_ts_1.Struct {
    getCellOrder() { return capnp_ts_1.Struct.getText(0, this); }
    setCellOrder(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptDimensions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownDimensions() { return capnp_ts_1.Struct.disown(this.getDimensions()); }
    getDimensions() { return capnp_ts_1.Struct.getList(1, Domain._Dimensions, this); }
    hasDimensions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initDimensions(length) { return capnp_ts_1.Struct.initList(1, Domain._Dimensions, length, this); }
    setDimensions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getTileOrder() { return capnp_ts_1.Struct.getText(2, this); }
    setTileOrder(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getType() { return capnp_ts_1.Struct.getText(3, this); }
    setType(value) { capnp_ts_1.Struct.setText(3, value, this); }
    toString() { return "Domain_" + super.toString(); }
}
exports.Domain = Domain;
Domain._capnp = { displayName: "Domain", id: "f8ef6fb69336c12f", size: new capnp_ts_1.ObjectSize(0, 4) };
class Array extends capnp_ts_1.Struct {
    getEndTimestamp() { return capnp_ts_1.Struct.getUint64(0, this); }
    setEndTimestamp(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getQueryType() { return capnp_ts_1.Struct.getText(0, this); }
    setQueryType(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getUri() { return capnp_ts_1.Struct.getText(1, this); }
    setUri(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getStartTimestamp() { return capnp_ts_1.Struct.getUint64(8, this); }
    setStartTimestamp(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    adoptArraySchemaLatest(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownArraySchemaLatest() { return capnp_ts_1.Struct.disown(this.getArraySchemaLatest()); }
    getArraySchemaLatest() { return capnp_ts_1.Struct.getStruct(2, ArraySchema, this); }
    hasArraySchemaLatest() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initArraySchemaLatest() { return capnp_ts_1.Struct.initStructAt(2, ArraySchema, this); }
    setArraySchemaLatest(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptArraySchemasAll(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownArraySchemasAll() { return capnp_ts_1.Struct.disown(this.getArraySchemasAll()); }
    getArraySchemasAll() { return capnp_ts_1.Struct.getStruct(3, ArraySchemaMap, this); }
    hasArraySchemasAll() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initArraySchemasAll() { return capnp_ts_1.Struct.initStructAt(3, ArraySchemaMap, this); }
    setArraySchemasAll(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptNonEmptyDomain(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownNonEmptyDomain() { return capnp_ts_1.Struct.disown(this.getNonEmptyDomain()); }
    getNonEmptyDomain() { return capnp_ts_1.Struct.getStruct(4, NonEmptyDomainList, this); }
    hasNonEmptyDomain() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initNonEmptyDomain() { return capnp_ts_1.Struct.initStructAt(4, NonEmptyDomainList, this); }
    setNonEmptyDomain(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptArrayMetadata(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownArrayMetadata() { return capnp_ts_1.Struct.disown(this.getArrayMetadata()); }
    getArrayMetadata() { return capnp_ts_1.Struct.getStruct(5, ArrayMetadata, this); }
    hasArrayMetadata() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initArrayMetadata() { return capnp_ts_1.Struct.initStructAt(5, ArrayMetadata, this); }
    setArrayMetadata(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    toString() { return "Array_" + super.toString(); }
}
exports.Array = Array;
Array._capnp = { displayName: "Array", id: "e8b44da5a3b284a4", size: new capnp_ts_1.ObjectSize(16, 6) };
class ArrayOpen extends capnp_ts_1.Struct {
    adoptConfig(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownConfig() { return capnp_ts_1.Struct.disown(this.getConfig()); }
    getConfig() { return capnp_ts_1.Struct.getStruct(0, Config, this); }
    hasConfig() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initConfig() { return capnp_ts_1.Struct.initStructAt(0, Config, this); }
    setConfig(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getQueryType() { return capnp_ts_1.Struct.getText(1, this); }
    setQueryType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "ArrayOpen_" + super.toString(); }
}
exports.ArrayOpen = ArrayOpen;
ArrayOpen._capnp = { displayName: "ArrayOpen", id: "98080e8276f32101", size: new capnp_ts_1.ObjectSize(0, 2) };
class ArraySchema extends capnp_ts_1.Struct {
    getArrayType() { return capnp_ts_1.Struct.getText(0, this); }
    setArrayType(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptAttributes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownAttributes() { return capnp_ts_1.Struct.disown(this.getAttributes()); }
    getAttributes() { return capnp_ts_1.Struct.getList(1, ArraySchema._Attributes, this); }
    hasAttributes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initAttributes(length) { return capnp_ts_1.Struct.initList(1, ArraySchema._Attributes, length, this); }
    setAttributes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getCapacity() { return capnp_ts_1.Struct.getUint64(0, this); }
    setCapacity(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getCellOrder() { return capnp_ts_1.Struct.getText(2, this); }
    setCellOrder(value) { capnp_ts_1.Struct.setText(2, value, this); }
    adoptCoordsFilterPipeline(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownCoordsFilterPipeline() { return capnp_ts_1.Struct.disown(this.getCoordsFilterPipeline()); }
    getCoordsFilterPipeline() { return capnp_ts_1.Struct.getStruct(3, FilterPipeline, this); }
    hasCoordsFilterPipeline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initCoordsFilterPipeline() { return capnp_ts_1.Struct.initStructAt(3, FilterPipeline, this); }
    setCoordsFilterPipeline(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptDomain(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownDomain() { return capnp_ts_1.Struct.disown(this.getDomain()); }
    getDomain() { return capnp_ts_1.Struct.getStruct(4, Domain, this); }
    hasDomain() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initDomain() { return capnp_ts_1.Struct.initStructAt(4, Domain, this); }
    setDomain(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptOffsetFilterPipeline(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownOffsetFilterPipeline() { return capnp_ts_1.Struct.disown(this.getOffsetFilterPipeline()); }
    getOffsetFilterPipeline() { return capnp_ts_1.Struct.getStruct(5, FilterPipeline, this); }
    hasOffsetFilterPipeline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initOffsetFilterPipeline() { return capnp_ts_1.Struct.initStructAt(5, FilterPipeline, this); }
    setOffsetFilterPipeline(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    getTileOrder() { return capnp_ts_1.Struct.getText(6, this); }
    setTileOrder(value) { capnp_ts_1.Struct.setText(6, value, this); }
    getUri() { return capnp_ts_1.Struct.getText(7, this); }
    setUri(value) { capnp_ts_1.Struct.setText(7, value, this); }
    adoptVersion(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(8, this)); }
    disownVersion() { return capnp_ts_1.Struct.disown(this.getVersion()); }
    getVersion() { return capnp_ts_1.Struct.getList(8, capnp.Int32List, this); }
    hasVersion() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(8, this)); }
    initVersion(length) { return capnp_ts_1.Struct.initList(8, capnp.Int32List, length, this); }
    setVersion(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(8, this)); }
    getAllowsDuplicates() { return capnp_ts_1.Struct.getBit(64, this); }
    setAllowsDuplicates(value) { capnp_ts_1.Struct.setBit(64, value, this); }
    adoptValidityFilterPipeline(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this)); }
    disownValidityFilterPipeline() { return capnp_ts_1.Struct.disown(this.getValidityFilterPipeline()); }
    getValidityFilterPipeline() { return capnp_ts_1.Struct.getStruct(9, FilterPipeline, this); }
    hasValidityFilterPipeline() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initValidityFilterPipeline() { return capnp_ts_1.Struct.initStructAt(9, FilterPipeline, this); }
    setValidityFilterPipeline(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this)); }
    getName() { return capnp_ts_1.Struct.getText(10, this); }
    setName(value) { capnp_ts_1.Struct.setText(10, value, this); }
    adoptTimestampRange(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(11, this)); }
    disownTimestampRange() { return capnp_ts_1.Struct.disown(this.getTimestampRange()); }
    getTimestampRange() { return capnp_ts_1.Struct.getList(11, capnp.Uint64List, this); }
    hasTimestampRange() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(11, this)); }
    initTimestampRange(length) { return capnp_ts_1.Struct.initList(11, capnp.Uint64List, length, this); }
    setTimestampRange(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(11, this)); }
    toString() { return "ArraySchema_" + super.toString(); }
}
exports.ArraySchema = ArraySchema;
ArraySchema._capnp = { displayName: "ArraySchema", id: "e4e6fd8e4b4df3bd", size: new capnp_ts_1.ObjectSize(16, 12) };
var Filter_Data_Which;
(function (Filter_Data_Which) {
    Filter_Data_Which[Filter_Data_Which["TEXT"] = 0] = "TEXT";
    Filter_Data_Which[Filter_Data_Which["BYTES"] = 1] = "BYTES";
    Filter_Data_Which[Filter_Data_Which["INT8"] = 2] = "INT8";
    Filter_Data_Which[Filter_Data_Which["UINT8"] = 3] = "UINT8";
    Filter_Data_Which[Filter_Data_Which["INT16"] = 4] = "INT16";
    Filter_Data_Which[Filter_Data_Which["UINT16"] = 5] = "UINT16";
    Filter_Data_Which[Filter_Data_Which["INT32"] = 6] = "INT32";
    Filter_Data_Which[Filter_Data_Which["UINT32"] = 7] = "UINT32";
    Filter_Data_Which[Filter_Data_Which["INT64"] = 8] = "INT64";
    Filter_Data_Which[Filter_Data_Which["UINT64"] = 9] = "UINT64";
    Filter_Data_Which[Filter_Data_Which["FLOAT32"] = 10] = "FLOAT32";
    Filter_Data_Which[Filter_Data_Which["FLOAT64"] = 11] = "FLOAT64";
})(Filter_Data_Which = exports.Filter_Data_Which || (exports.Filter_Data_Which = {}));
class Filter_Data extends capnp_ts_1.Struct {
    getText() {
        capnp_ts_1.Struct.testWhich("text", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isText() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setText(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    adoptBytes(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownBytes() { return capnp_ts_1.Struct.disown(this.getBytes()); }
    getBytes() {
        capnp_ts_1.Struct.testWhich("bytes", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getData(1, this);
    }
    hasBytes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initBytes(length) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initData(1, length, this);
    }
    isBytes() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setBytes(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    getInt8() {
        capnp_ts_1.Struct.testWhich("int8", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getInt8(2, this);
    }
    isInt8() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setInt8(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setInt8(2, value, this);
    }
    getUint8() {
        capnp_ts_1.Struct.testWhich("uint8", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getUint8(2, this);
    }
    isUint8() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setUint8(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.setUint8(2, value, this);
    }
    getInt16() {
        capnp_ts_1.Struct.testWhich("int16", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getInt16(2, this);
    }
    isInt16() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setInt16(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.setInt16(2, value, this);
    }
    getUint16() {
        capnp_ts_1.Struct.testWhich("uint16", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getUint16(2, this);
    }
    isUint16() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setUint16(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.setUint16(2, value, this);
    }
    getInt32() {
        capnp_ts_1.Struct.testWhich("int32", capnp_ts_1.Struct.getUint16(0, this), 6, this);
        return capnp_ts_1.Struct.getInt32(4, this);
    }
    isInt32() { return capnp_ts_1.Struct.getUint16(0, this) === 6; }
    setInt32(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.setInt32(4, value, this);
    }
    getUint32() {
        capnp_ts_1.Struct.testWhich("uint32", capnp_ts_1.Struct.getUint16(0, this), 7, this);
        return capnp_ts_1.Struct.getUint32(4, this);
    }
    isUint32() { return capnp_ts_1.Struct.getUint16(0, this) === 7; }
    setUint32(value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.setUint32(4, value, this);
    }
    getInt64() {
        capnp_ts_1.Struct.testWhich("int64", capnp_ts_1.Struct.getUint16(0, this), 8, this);
        return capnp_ts_1.Struct.getInt64(8, this);
    }
    isInt64() { return capnp_ts_1.Struct.getUint16(0, this) === 8; }
    setInt64(value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.setInt64(8, value, this);
    }
    getUint64() {
        capnp_ts_1.Struct.testWhich("uint64", capnp_ts_1.Struct.getUint16(0, this), 9, this);
        return capnp_ts_1.Struct.getUint64(8, this);
    }
    isUint64() { return capnp_ts_1.Struct.getUint16(0, this) === 9; }
    setUint64(value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.setUint64(8, value, this);
    }
    getFloat32() {
        capnp_ts_1.Struct.testWhich("float32", capnp_ts_1.Struct.getUint16(0, this), 10, this);
        return capnp_ts_1.Struct.getFloat32(4, this);
    }
    isFloat32() { return capnp_ts_1.Struct.getUint16(0, this) === 10; }
    setFloat32(value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.setFloat32(4, value, this);
    }
    getFloat64() {
        capnp_ts_1.Struct.testWhich("float64", capnp_ts_1.Struct.getUint16(0, this), 11, this);
        return capnp_ts_1.Struct.getFloat64(8, this);
    }
    isFloat64() { return capnp_ts_1.Struct.getUint16(0, this) === 11; }
    setFloat64(value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.setFloat64(8, value, this);
    }
    toString() { return "Filter_Data_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Filter_Data = Filter_Data;
Filter_Data.TEXT = Filter_Data_Which.TEXT;
Filter_Data.BYTES = Filter_Data_Which.BYTES;
Filter_Data.INT8 = Filter_Data_Which.INT8;
Filter_Data.UINT8 = Filter_Data_Which.UINT8;
Filter_Data.INT16 = Filter_Data_Which.INT16;
Filter_Data.UINT16 = Filter_Data_Which.UINT16;
Filter_Data.INT32 = Filter_Data_Which.INT32;
Filter_Data.UINT32 = Filter_Data_Which.UINT32;
Filter_Data.INT64 = Filter_Data_Which.INT64;
Filter_Data.UINT64 = Filter_Data_Which.UINT64;
Filter_Data.FLOAT32 = Filter_Data_Which.FLOAT32;
Filter_Data.FLOAT64 = Filter_Data_Which.FLOAT64;
Filter_Data._capnp = { displayName: "data", id: "f7e88fec77255f9a", size: new capnp_ts_1.ObjectSize(16, 2) };
class Filter extends capnp_ts_1.Struct {
    getType() { return capnp_ts_1.Struct.getText(0, this); }
    setType(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getData() { return capnp_ts_1.Struct.getAs(Filter_Data, this); }
    initData() { return capnp_ts_1.Struct.getAs(Filter_Data, this); }
    toString() { return "Filter_" + super.toString(); }
}
exports.Filter = Filter;
Filter._capnp = { displayName: "Filter", id: "dac88a0a3b53a50a", size: new capnp_ts_1.ObjectSize(16, 2) };
class FilterPipeline extends capnp_ts_1.Struct {
    adoptFilters(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownFilters() { return capnp_ts_1.Struct.disown(this.getFilters()); }
    getFilters() { return capnp_ts_1.Struct.getList(0, FilterPipeline._Filters, this); }
    hasFilters() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initFilters(length) { return capnp_ts_1.Struct.initList(0, FilterPipeline._Filters, length, this); }
    setFilters(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "FilterPipeline_" + super.toString(); }
}
exports.FilterPipeline = FilterPipeline;
FilterPipeline._capnp = { displayName: "FilterPipeline", id: "a6d903a3c84d4809", size: new capnp_ts_1.ObjectSize(0, 1) };
class ArraySchemaMap_Entry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getStruct(1, ArraySchema, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initValue() { return capnp_ts_1.Struct.initStructAt(1, ArraySchema, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "ArraySchemaMap_Entry_" + super.toString(); }
}
exports.ArraySchemaMap_Entry = ArraySchemaMap_Entry;
ArraySchemaMap_Entry._capnp = { displayName: "Entry", id: "f6918b8d3d6aaece", size: new capnp_ts_1.ObjectSize(0, 2) };
class ArraySchemaMap extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, ArraySchemaMap._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, ArraySchemaMap._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ArraySchemaMap_" + super.toString(); }
}
exports.ArraySchemaMap = ArraySchemaMap;
ArraySchemaMap.Entry = ArraySchemaMap_Entry;
ArraySchemaMap._capnp = { displayName: "ArraySchemaMap", id: "fd01f8198120e948", size: new capnp_ts_1.ObjectSize(0, 1) };
class Map_Entry extends capnp_ts_1.Struct {
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getPointer(0, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getPointer(1, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Map_Entry_" + super.toString(); }
}
exports.Map_Entry = Map_Entry;
Map_Entry._capnp = { displayName: "Entry", id: "9d58857f4eaf2e0b", size: new capnp_ts_1.ObjectSize(0, 2) };
class Map extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, Map._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, Map._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Map_" + super.toString(); }
}
exports.Map = Map;
Map.Entry = Map_Entry;
Map._capnp = { displayName: "Map", id: "d49ce2e3753dec00", size: new capnp_ts_1.ObjectSize(0, 1) };
class KV extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getText(1, this); }
    setValue(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "KV_" + super.toString(); }
}
exports.KV = KV;
KV._capnp = { displayName: "KV", id: "f81811af0443b7bd", size: new capnp_ts_1.ObjectSize(0, 2) };
class Config extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, Config._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, Config._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Config_" + super.toString(); }
}
exports.Config = Config;
Config._capnp = { displayName: "Config", id: "84e9e25074e7b66d", size: new capnp_ts_1.ObjectSize(0, 1) };
class Stats extends capnp_ts_1.Struct {
    adoptTimers(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTimers() { return capnp_ts_1.Struct.disown(this.getTimers()); }
    getTimers() { return capnp_ts_1.Struct.getStruct(0, MapFloat64, this); }
    hasTimers() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTimers() { return capnp_ts_1.Struct.initStructAt(0, MapFloat64, this); }
    setTimers(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptCounters(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownCounters() { return capnp_ts_1.Struct.disown(this.getCounters()); }
    getCounters() { return capnp_ts_1.Struct.getStruct(1, MapUInt64, this); }
    hasCounters() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initCounters() { return capnp_ts_1.Struct.initStructAt(1, MapUInt64, this); }
    setCounters(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Stats_" + super.toString(); }
}
exports.Stats = Stats;
Stats._capnp = { displayName: "Stats", id: "ef6314d713d0ab34", size: new capnp_ts_1.ObjectSize(0, 2) };
class Writer extends capnp_ts_1.Struct {
    getCheckCoordDups() { return capnp_ts_1.Struct.getBit(0, this); }
    setCheckCoordDups(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getCheckCoordOOB() { return capnp_ts_1.Struct.getBit(1, this); }
    setCheckCoordOOB(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getDedupCoords() { return capnp_ts_1.Struct.getBit(2, this); }
    setDedupCoords(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    adoptSubarray(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSubarray() { return capnp_ts_1.Struct.disown(this.getSubarray()); }
    getSubarray() { return capnp_ts_1.Struct.getStruct(0, DomainArray, this); }
    hasSubarray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSubarray() { return capnp_ts_1.Struct.initStructAt(0, DomainArray, this); }
    setSubarray(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptSubarrayRanges(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSubarrayRanges() { return capnp_ts_1.Struct.disown(this.getSubarrayRanges()); }
    getSubarrayRanges() { return capnp_ts_1.Struct.getStruct(1, Subarray, this); }
    hasSubarrayRanges() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSubarrayRanges() { return capnp_ts_1.Struct.initStructAt(1, Subarray, this); }
    setSubarrayRanges(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptStats(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownStats() { return capnp_ts_1.Struct.disown(this.getStats()); }
    getStats() { return capnp_ts_1.Struct.getStruct(2, Stats, this); }
    hasStats() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initStats() { return capnp_ts_1.Struct.initStructAt(2, Stats, this); }
    setStats(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Writer_" + super.toString(); }
}
exports.Writer = Writer;
Writer._capnp = { displayName: "Writer", id: "fe68eabb8ab4dcfa", size: new capnp_ts_1.ObjectSize(8, 3) };
class QueryReader extends capnp_ts_1.Struct {
    getLayout() { return capnp_ts_1.Struct.getText(0, this); }
    setLayout(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptSubarray(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSubarray() { return capnp_ts_1.Struct.disown(this.getSubarray()); }
    getSubarray() { return capnp_ts_1.Struct.getStruct(1, Subarray, this); }
    hasSubarray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSubarray() { return capnp_ts_1.Struct.initStructAt(1, Subarray, this); }
    setSubarray(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptReadState(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownReadState() { return capnp_ts_1.Struct.disown(this.getReadState()); }
    getReadState() { return capnp_ts_1.Struct.getStruct(2, ReadState, this); }
    hasReadState() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initReadState() { return capnp_ts_1.Struct.initStructAt(2, ReadState, this); }
    setReadState(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptCondition(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownCondition() { return capnp_ts_1.Struct.disown(this.getCondition()); }
    getCondition() { return capnp_ts_1.Struct.getStruct(3, Condition, this); }
    hasCondition() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initCondition() { return capnp_ts_1.Struct.initStructAt(3, Condition, this); }
    setCondition(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptStats(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownStats() { return capnp_ts_1.Struct.disown(this.getStats()); }
    getStats() { return capnp_ts_1.Struct.getStruct(4, Stats, this); }
    hasStats() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initStats() { return capnp_ts_1.Struct.initStructAt(4, Stats, this); }
    setStats(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "QueryReader_" + super.toString(); }
}
exports.QueryReader = QueryReader;
QueryReader._capnp = { displayName: "QueryReader", id: "97a817df79d1095d", size: new capnp_ts_1.ObjectSize(0, 5) };
class SubarrayRanges extends capnp_ts_1.Struct {
    getType() { return capnp_ts_1.Struct.getText(0, this); }
    setType(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getHasDefaultRange() { return capnp_ts_1.Struct.getBit(0, this); }
    setHasDefaultRange(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    adoptBuffer(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownBuffer() { return capnp_ts_1.Struct.disown(this.getBuffer()); }
    getBuffer() { return capnp_ts_1.Struct.getData(1, this); }
    hasBuffer() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initBuffer(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setBuffer(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptBufferSizes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownBufferSizes() { return capnp_ts_1.Struct.disown(this.getBufferSizes()); }
    getBufferSizes() { return capnp_ts_1.Struct.getList(2, capnp.Uint64List, this); }
    hasBufferSizes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initBufferSizes(length) { return capnp_ts_1.Struct.initList(2, capnp.Uint64List, length, this); }
    setBufferSizes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptBufferStartSizes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownBufferStartSizes() { return capnp_ts_1.Struct.disown(this.getBufferStartSizes()); }
    getBufferStartSizes() { return capnp_ts_1.Struct.getList(3, capnp.Uint64List, this); }
    hasBufferStartSizes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initBufferStartSizes(length) { return capnp_ts_1.Struct.initList(3, capnp.Uint64List, length, this); }
    setBufferStartSizes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "SubarrayRanges_" + super.toString(); }
}
exports.SubarrayRanges = SubarrayRanges;
SubarrayRanges._capnp = { displayName: "SubarrayRanges", id: "8587733f29e10a41", size: new capnp_ts_1.ObjectSize(8, 4) };
class Subarray extends capnp_ts_1.Struct {
    getLayout() { return capnp_ts_1.Struct.getText(0, this); }
    setLayout(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptRanges(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownRanges() { return capnp_ts_1.Struct.disown(this.getRanges()); }
    getRanges() { return capnp_ts_1.Struct.getList(1, Subarray._Ranges, this); }
    hasRanges() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initRanges(length) { return capnp_ts_1.Struct.initList(1, Subarray._Ranges, length, this); }
    setRanges(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptStats(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownStats() { return capnp_ts_1.Struct.disown(this.getStats()); }
    getStats() { return capnp_ts_1.Struct.getStruct(2, Stats, this); }
    hasStats() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initStats() { return capnp_ts_1.Struct.initStructAt(2, Stats, this); }
    setStats(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Subarray_" + super.toString(); }
}
exports.Subarray = Subarray;
Subarray._capnp = { displayName: "Subarray", id: "da36de34a7124afb", size: new capnp_ts_1.ObjectSize(0, 3) };
class SubarrayPartitioner_PartitionInfo extends capnp_ts_1.Struct {
    adoptSubarray(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSubarray() { return capnp_ts_1.Struct.disown(this.getSubarray()); }
    getSubarray() { return capnp_ts_1.Struct.getStruct(0, Subarray, this); }
    hasSubarray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSubarray() { return capnp_ts_1.Struct.initStructAt(0, Subarray, this); }
    setSubarray(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getStart() { return capnp_ts_1.Struct.getUint64(0, this); }
    setStart(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getEnd() { return capnp_ts_1.Struct.getUint64(8, this); }
    setEnd(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getSplitMultiRange() { return capnp_ts_1.Struct.getBit(128, this); }
    setSplitMultiRange(value) { capnp_ts_1.Struct.setBit(128, value, this); }
    toString() { return "SubarrayPartitioner_PartitionInfo_" + super.toString(); }
}
exports.SubarrayPartitioner_PartitionInfo = SubarrayPartitioner_PartitionInfo;
SubarrayPartitioner_PartitionInfo._capnp = { displayName: "PartitionInfo", id: "c195bcd1baa34c68", size: new capnp_ts_1.ObjectSize(24, 1) };
class SubarrayPartitioner_State extends capnp_ts_1.Struct {
    getStart() { return capnp_ts_1.Struct.getUint64(0, this); }
    setStart(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getEnd() { return capnp_ts_1.Struct.getUint64(8, this); }
    setEnd(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    adoptSingleRange(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSingleRange() { return capnp_ts_1.Struct.disown(this.getSingleRange()); }
    getSingleRange() { return capnp_ts_1.Struct.getList(0, SubarrayPartitioner_State._SingleRange, this); }
    hasSingleRange() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSingleRange(length) { return capnp_ts_1.Struct.initList(0, SubarrayPartitioner_State._SingleRange, length, this); }
    setSingleRange(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptMultiRange(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownMultiRange() { return capnp_ts_1.Struct.disown(this.getMultiRange()); }
    getMultiRange() { return capnp_ts_1.Struct.getList(1, SubarrayPartitioner_State._MultiRange, this); }
    hasMultiRange() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initMultiRange(length) { return capnp_ts_1.Struct.initList(1, SubarrayPartitioner_State._MultiRange, length, this); }
    setMultiRange(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "SubarrayPartitioner_State_" + super.toString(); }
}
exports.SubarrayPartitioner_State = SubarrayPartitioner_State;
SubarrayPartitioner_State._capnp = { displayName: "State", id: "cbd6edafbf7bb215", size: new capnp_ts_1.ObjectSize(16, 2) };
class SubarrayPartitioner extends capnp_ts_1.Struct {
    adoptSubarray(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSubarray() { return capnp_ts_1.Struct.disown(this.getSubarray()); }
    getSubarray() { return capnp_ts_1.Struct.getStruct(0, Subarray, this); }
    hasSubarray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSubarray() { return capnp_ts_1.Struct.initStructAt(0, Subarray, this); }
    setSubarray(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptBudget(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownBudget() { return capnp_ts_1.Struct.disown(this.getBudget()); }
    getBudget() { return capnp_ts_1.Struct.getList(1, SubarrayPartitioner._Budget, this); }
    hasBudget() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initBudget(length) { return capnp_ts_1.Struct.initList(1, SubarrayPartitioner._Budget, length, this); }
    setBudget(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptCurrent(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownCurrent() { return capnp_ts_1.Struct.disown(this.getCurrent()); }
    getCurrent() { return capnp_ts_1.Struct.getStruct(2, SubarrayPartitioner_PartitionInfo, this); }
    hasCurrent() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initCurrent() { return capnp_ts_1.Struct.initStructAt(2, SubarrayPartitioner_PartitionInfo, this); }
    setCurrent(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptState(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownState() { return capnp_ts_1.Struct.disown(this.getState()); }
    getState() { return capnp_ts_1.Struct.getStruct(3, SubarrayPartitioner_State, this); }
    hasState() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initState() { return capnp_ts_1.Struct.initStructAt(3, SubarrayPartitioner_State, this); }
    setState(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    getMemoryBudget() { return capnp_ts_1.Struct.getUint64(0, this); }
    setMemoryBudget(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getMemoryBudgetVar() { return capnp_ts_1.Struct.getUint64(8, this); }
    setMemoryBudgetVar(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getMemoryBudgetValidity() { return capnp_ts_1.Struct.getUint64(16, this); }
    setMemoryBudgetValidity(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    adoptStats(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownStats() { return capnp_ts_1.Struct.disown(this.getStats()); }
    getStats() { return capnp_ts_1.Struct.getStruct(4, Stats, this); }
    hasStats() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initStats() { return capnp_ts_1.Struct.initStructAt(4, Stats, this); }
    setStats(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "SubarrayPartitioner_" + super.toString(); }
}
exports.SubarrayPartitioner = SubarrayPartitioner;
SubarrayPartitioner.PartitionInfo = SubarrayPartitioner_PartitionInfo;
SubarrayPartitioner.State = SubarrayPartitioner_State;
SubarrayPartitioner._capnp = { displayName: "SubarrayPartitioner", id: "98222aaeac2b06c0", size: new capnp_ts_1.ObjectSize(24, 5) };
class ReadState extends capnp_ts_1.Struct {
    getOverflowed() { return capnp_ts_1.Struct.getBit(0, this); }
    setOverflowed(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getUnsplittable() { return capnp_ts_1.Struct.getBit(1, this); }
    setUnsplittable(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getInitialized() { return capnp_ts_1.Struct.getBit(2, this); }
    setInitialized(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    adoptSubarrayPartitioner(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSubarrayPartitioner() { return capnp_ts_1.Struct.disown(this.getSubarrayPartitioner()); }
    getSubarrayPartitioner() { return capnp_ts_1.Struct.getStruct(0, SubarrayPartitioner, this); }
    hasSubarrayPartitioner() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSubarrayPartitioner() { return capnp_ts_1.Struct.initStructAt(0, SubarrayPartitioner, this); }
    setSubarrayPartitioner(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ReadState_" + super.toString(); }
}
exports.ReadState = ReadState;
ReadState._capnp = { displayName: "ReadState", id: "910b5afbbc6a0745", size: new capnp_ts_1.ObjectSize(8, 1) };
class ConditionClause extends capnp_ts_1.Struct {
    getFieldName() { return capnp_ts_1.Struct.getText(0, this); }
    setFieldName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(1, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getOp() { return capnp_ts_1.Struct.getText(2, this); }
    setOp(value) { capnp_ts_1.Struct.setText(2, value, this); }
    toString() { return "ConditionClause_" + super.toString(); }
}
exports.ConditionClause = ConditionClause;
ConditionClause._capnp = { displayName: "ConditionClause", id: "fa99a0f16eaa03a5", size: new capnp_ts_1.ObjectSize(0, 3) };
class Condition extends capnp_ts_1.Struct {
    adoptClauses(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownClauses() { return capnp_ts_1.Struct.disown(this.getClauses()); }
    getClauses() { return capnp_ts_1.Struct.getList(0, Condition._Clauses, this); }
    hasClauses() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initClauses(length) { return capnp_ts_1.Struct.initList(0, Condition._Clauses, length, this); }
    setClauses(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptClauseCombinationOps(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownClauseCombinationOps() { return capnp_ts_1.Struct.disown(this.getClauseCombinationOps()); }
    getClauseCombinationOps() { return capnp_ts_1.Struct.getList(1, capnp.TextList, this); }
    hasClauseCombinationOps() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initClauseCombinationOps(length) { return capnp_ts_1.Struct.initList(1, capnp.TextList, length, this); }
    setClauseCombinationOps(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Condition_" + super.toString(); }
}
exports.Condition = Condition;
Condition._capnp = { displayName: "Condition", id: "fb156e2d8b8f4cf3", size: new capnp_ts_1.ObjectSize(0, 2) };
class DomainArray extends capnp_ts_1.Struct {
    adoptInt8(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownInt8() { return capnp_ts_1.Struct.disown(this.getInt8()); }
    getInt8() { return capnp_ts_1.Struct.getList(0, capnp.Int8List, this); }
    hasInt8() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initInt8(length) { return capnp_ts_1.Struct.initList(0, capnp.Int8List, length, this); }
    setInt8(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptUint8(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownUint8() { return capnp_ts_1.Struct.disown(this.getUint8()); }
    getUint8() { return capnp_ts_1.Struct.getList(1, capnp.Uint8List, this); }
    hasUint8() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initUint8(length) { return capnp_ts_1.Struct.initList(1, capnp.Uint8List, length, this); }
    setUint8(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptInt16(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownInt16() { return capnp_ts_1.Struct.disown(this.getInt16()); }
    getInt16() { return capnp_ts_1.Struct.getList(2, capnp.Int16List, this); }
    hasInt16() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initInt16(length) { return capnp_ts_1.Struct.initList(2, capnp.Int16List, length, this); }
    setInt16(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptUint16(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownUint16() { return capnp_ts_1.Struct.disown(this.getUint16()); }
    getUint16() { return capnp_ts_1.Struct.getList(3, capnp.Uint16List, this); }
    hasUint16() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initUint16(length) { return capnp_ts_1.Struct.initList(3, capnp.Uint16List, length, this); }
    setUint16(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptInt32(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownInt32() { return capnp_ts_1.Struct.disown(this.getInt32()); }
    getInt32() { return capnp_ts_1.Struct.getList(4, capnp.Int32List, this); }
    hasInt32() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initInt32(length) { return capnp_ts_1.Struct.initList(4, capnp.Int32List, length, this); }
    setInt32(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptUint32(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownUint32() { return capnp_ts_1.Struct.disown(this.getUint32()); }
    getUint32() { return capnp_ts_1.Struct.getList(5, capnp.Uint32List, this); }
    hasUint32() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initUint32(length) { return capnp_ts_1.Struct.initList(5, capnp.Uint32List, length, this); }
    setUint32(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    adoptInt64(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(6, this)); }
    disownInt64() { return capnp_ts_1.Struct.disown(this.getInt64()); }
    getInt64() { return capnp_ts_1.Struct.getList(6, capnp.Int64List, this); }
    hasInt64() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(6, this)); }
    initInt64(length) { return capnp_ts_1.Struct.initList(6, capnp.Int64List, length, this); }
    setInt64(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(6, this)); }
    adoptUint64(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(7, this)); }
    disownUint64() { return capnp_ts_1.Struct.disown(this.getUint64()); }
    getUint64() { return capnp_ts_1.Struct.getList(7, capnp.Uint64List, this); }
    hasUint64() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(7, this)); }
    initUint64(length) { return capnp_ts_1.Struct.initList(7, capnp.Uint64List, length, this); }
    setUint64(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(7, this)); }
    adoptFloat32(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(8, this)); }
    disownFloat32() { return capnp_ts_1.Struct.disown(this.getFloat32()); }
    getFloat32() { return capnp_ts_1.Struct.getList(8, capnp.Float32List, this); }
    hasFloat32() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(8, this)); }
    initFloat32(length) { return capnp_ts_1.Struct.initList(8, capnp.Float32List, length, this); }
    setFloat32(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(8, this)); }
    adoptFloat64(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this)); }
    disownFloat64() { return capnp_ts_1.Struct.disown(this.getFloat64()); }
    getFloat64() { return capnp_ts_1.Struct.getList(9, capnp.Float64List, this); }
    hasFloat64() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initFloat64(length) { return capnp_ts_1.Struct.initList(9, capnp.Float64List, length, this); }
    setFloat64(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this)); }
    toString() { return "DomainArray_" + super.toString(); }
}
exports.DomainArray = DomainArray;
DomainArray._capnp = { displayName: "DomainArray", id: "bc387f87af7fdffb", size: new capnp_ts_1.ObjectSize(0, 10) };
class MapFloat64_Entry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getFloat64(0, this); }
    setValue(value) { capnp_ts_1.Struct.setFloat64(0, value, this); }
    toString() { return "MapFloat64_Entry_" + super.toString(); }
}
exports.MapFloat64_Entry = MapFloat64_Entry;
MapFloat64_Entry._capnp = { displayName: "Entry", id: "bc6fa37d7f8e67b0", size: new capnp_ts_1.ObjectSize(8, 1) };
class MapFloat64 extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, MapFloat64._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, MapFloat64._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MapFloat64_" + super.toString(); }
}
exports.MapFloat64 = MapFloat64;
MapFloat64.Entry = MapFloat64_Entry;
MapFloat64._capnp = { displayName: "MapFloat64", id: "a240366668f18d8e", size: new capnp_ts_1.ObjectSize(0, 1) };
class MapUInt64_Entry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getUint64(0, this); }
    setValue(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "MapUInt64_Entry_" + super.toString(); }
}
exports.MapUInt64_Entry = MapUInt64_Entry;
MapUInt64_Entry._capnp = { displayName: "Entry", id: "977674438c18071e", size: new capnp_ts_1.ObjectSize(8, 1) };
class MapUInt64 extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, MapUInt64._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, MapUInt64._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "MapUInt64_" + super.toString(); }
}
exports.MapUInt64 = MapUInt64;
MapUInt64.Entry = MapUInt64_Entry;
MapUInt64._capnp = { displayName: "MapUInt64", id: "de734faff53aa239", size: new capnp_ts_1.ObjectSize(0, 1) };
class AttributeBufferSize extends capnp_ts_1.Struct {
    getAttribute() { return capnp_ts_1.Struct.getText(0, this); }
    setAttribute(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getOffsetBytes() { return capnp_ts_1.Struct.getUint64(0, this); }
    setOffsetBytes(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getDataBytes() { return capnp_ts_1.Struct.getUint64(8, this); }
    setDataBytes(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getValidityBytes() { return capnp_ts_1.Struct.getUint64(16, this); }
    setValidityBytes(value) { capnp_ts_1.Struct.setUint64(16, value, this); }
    toString() { return "AttributeBufferSize_" + super.toString(); }
}
exports.AttributeBufferSize = AttributeBufferSize;
AttributeBufferSize._capnp = { displayName: "AttributeBufferSize", id: "e8c3366db226bb6a", size: new capnp_ts_1.ObjectSize(24, 1) };
class ArrayMetadata_MetadataEntry extends capnp_ts_1.Struct {
    getKey() { return capnp_ts_1.Struct.getText(0, this); }
    setKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getType() { return capnp_ts_1.Struct.getText(1, this); }
    setType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getValueNum() { return capnp_ts_1.Struct.getUint32(0, this); }
    setValueNum(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getData(2, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initValue(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getDel() { return capnp_ts_1.Struct.getBit(32, this); }
    setDel(value) { capnp_ts_1.Struct.setBit(32, value, this); }
    toString() { return "ArrayMetadata_MetadataEntry_" + super.toString(); }
}
exports.ArrayMetadata_MetadataEntry = ArrayMetadata_MetadataEntry;
ArrayMetadata_MetadataEntry._capnp = { displayName: "MetadataEntry", id: "dc11d0ec5c20f3f9", size: new capnp_ts_1.ObjectSize(8, 3) };
class ArrayMetadata extends capnp_ts_1.Struct {
    adoptEntries(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownEntries() { return capnp_ts_1.Struct.disown(this.getEntries()); }
    getEntries() { return capnp_ts_1.Struct.getList(0, ArrayMetadata._Entries, this); }
    hasEntries() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initEntries(length) { return capnp_ts_1.Struct.initList(0, ArrayMetadata._Entries, length, this); }
    setEntries(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "ArrayMetadata_" + super.toString(); }
}
exports.ArrayMetadata = ArrayMetadata;
ArrayMetadata.MetadataEntry = ArrayMetadata_MetadataEntry;
ArrayMetadata._capnp = { displayName: "ArrayMetadata", id: "b34f96d2ab41185f", size: new capnp_ts_1.ObjectSize(0, 1) };
Query._AttributeBufferHeaders = capnp.CompositeList(AttributeBufferHeader);
NonEmptyDomainList._NonEmptyDomains = capnp.CompositeList(NonEmptyDomain);
Domain._Dimensions = capnp.CompositeList(Dimension);
ArraySchema._Attributes = capnp.CompositeList(Attribute);
FilterPipeline._Filters = capnp.CompositeList(Filter);
ArraySchemaMap._Entries = capnp.CompositeList(ArraySchemaMap_Entry);
Map._Entries = capnp.CompositeList(Map_Entry);
Config._Entries = capnp.CompositeList(KV);
Subarray._Ranges = capnp.CompositeList(SubarrayRanges);
SubarrayPartitioner_State._SingleRange = capnp.CompositeList(Subarray);
SubarrayPartitioner_State._MultiRange = capnp.CompositeList(Subarray);
SubarrayPartitioner._Budget = capnp.CompositeList(AttributeBufferSize);
Condition._Clauses = capnp.CompositeList(ConditionClause);
MapFloat64._Entries = capnp.CompositeList(MapFloat64_Entry);
MapUInt64._Entries = capnp.CompositeList(MapUInt64_Entry);
ArrayMetadata._Entries = capnp.CompositeList(ArrayMetadata_MetadataEntry);
//# sourceMappingURL=query_capnp.js.map